/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jemepousse (https://sketchfab.com/jemepousse)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/356c773c4b9a45d8b9d4aa04c60ecb27
Title: Red City
*/

import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function CityModel(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF("/scene-draco.glb") as any;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group position={[-102253.523, -210688.859, -17050.523]}>
					<mesh
						castShadow
						receiveShadow
						geometry={(nodes.mesh_0 as THREE.Mesh).geometry}
						material={materials.Scene_Root}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={(nodes.mesh_1 as THREE.Mesh).geometry}
						material={materials.Scene_Root}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={(nodes.mesh_2 as THREE.Mesh).geometry}
						material={materials.Scene_Root}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={(nodes.mesh_3 as THREE.Mesh).geometry}
						material={materials.Scene_Root}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/scene-draco.glb");
