/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function EgpytModel(props: any) {
	const { nodes, materials } = useGLTF("/egpyt.glb") as any;
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nha_Phu_1.geometry}
					material={materials.polySurface101SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nha_Phu_2.geometry}
					material={materials.O_Nen_v1SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nha_Phu_3.geometry}
					material={materials.O_Nen_v2SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Nha_Phu_4.geometry}
					material={materials.O_Nen_v3SG}
				/>
			</group>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.NhaChinh_1.geometry}
					material={materials.A_LSG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.NhaChinh_2.geometry}
					material={materials.A_LSG1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.NhaChinh_3.geometry}
					material={materials.A_LSG2}
				/>
			</group>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.O_nen_1.geometry}
					material={materials.polySurface91SG}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.O_nen_2.geometry}
					material={materials.polySurface66SG}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/egpyt.glb");
