import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "3d examples",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Link href="/model">
					<div
						className="absolute top-0 left-0 p-4 m-2
						rounded-full size-16 flex flex-col justify-center 
						items-center  bg-blue-200 text-blue-600 z-999
						font-bold"
					>
						Home
					</div>
				</Link>
				{children}
			</body>
		</html>
	);
}
